version: 2
jobs:
  deploy-stage:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d9:69:23:09:31:c2:71:94:73:a1:05:03:f4:14:63:d7" #上記メモったハッシュを指定
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_STG_HOST "/var/www/Live-study/deploy.sh"
  deploy-prod:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:38:05:59:17:c5:db:84:ab:d1:fa:04:9c:8b:ab:e6" #上記メモったハッシュを指定
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/Live-study/deploy.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-stage
          # filters:
          #   branches:
          #     only: staging
      - deploy-prod:
          filters:
            branches:
              only: master