version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/live_study 
    steps:
      - checkout
      - run: # circleci の ruby のコンテナの bundler のバージョンは古いので update する
          name: bundle update
          command: gem install bundler:2.0.2 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }} 
            - v1-dependencies-
      - run:
          name: install dependencies 
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle 
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  
    #push for ecr
  build_image:
    docker:
      - image: docker:18.09.0
    steps:
    - checkout
    - setup_remote_docker 
    - run:
        name: install aws cli
        command: |
          apk add --no-cache --update py-pip
          pip install awscli 
    - run:
        name: build image
        command: |
          $(aws ecr get-login --no-include-email --region ap-northeast-1)
          docker build -t ${ECR_DOMAIN}/sample-image:$ CIRCLE_ SHA 1 -t ${ECR_DOMAIN}/sample-image:latest --build-arg RAILS_ MASTER_ KEY =${RAILS_MASTER_KEY} --build-arg RAILS_ENV=production .
    - run:
        name: Push docker image 
        command: |
          docker push ${ECR_DOMAIN}/sample-image:$CIRCLE_SHA1 
          docker push ${ECR_DOMAIN}/sample-image:latest

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

# workflows:
#   version: 2
#   test:
#     jobs:
#       - build
#       - build_image: 
#         requires: 
#           - build
#         filters:
#           branches:
#             only: master