- name: Add repository
  yum_repository:
      name: MariaDB
      description: MariaDB repo
      baseurl: http://yum.mariadb.org/10.3/rhel7-amd64
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: true
      # MariaDBのインストール
- name: Install MariaDB server
  yum:
    name: MariaDB-server
    state: present

- name: MariaDb shared
  yum:
    name: MariaDB-shared 
# 起動および自動起動設定
- name: Start MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes