default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER")%>
  password: <%= ENV.fetch("DATABASE_PASSWORD")%> 
  socket: <%= ENV.fetch("DATABASE_SOCKET")%> 

development:
  <<: *default
  database: Live_study_development
  password: <%= ENV.fetch("DATABASE_PASSWORD")%> 
  host: <%= ENV.fetch("DATABASE_HOST")%>

test:
  <<: *default
  database: Live_study_test

staging: 
  <<: *default
  database: Live_study_staging

production:
  <<: *default
  database: Live_study_production
