- name: install nodejs
  shell: |
    curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -

- name: yum js      
  yum: name={{ item }} state=installed
  with_items:
    - nodejs
    
- name: Install yarn package
  get_url: url="https://dl.yarnpkg.com/rpm/yarn.repo" dest=/etc/yum.repos.d/yarn.repo

- name: install yarn
  npm:
    name: yarn
    state: present
    global: yes  