- name: Install openssl
  yum: name=openssl-devel

- name: Enable to install NGINX.
  shell: "amazon-linux-extras enable nginx1"
  become: yes

- name: Install NGINX.
  yum: name=nginx

- name: copy nginx conf
  copy:
    src: nginx.conf 
    dest: /etc/nginx/

- name: copy stg.live-study.work.conf
  copy:
    src: stg.live-study.work.conf
    dest: /etc/nginx/conf.d/

- command: chkconfig nginx on
- command: service nginx restart