- name: Install openssl
  yum: name=openssl-devel

- name: Enable to install NGINX.
  shell: "amazon-linux-extras enable nginx1"
  become: yes

- name: Install NGINX.
  yum: name=nginx

- name: nginx start
  systemd:
    state: started
    name: nginx
    enabled: yes
    
- name: copy nginx conf
  copy:
    src: roles/nginx/files/{{ item.src }}
    dest: /etc/nginx/
  with_items:  
    - { src: "{{ inventory_hostname }}/nginx.conf" }

- name: copy stg.live-study.work.conf
  copy:
    src: roles/nginx/files/{{ item.src }}
    dest: /etc/nginx/conf.d/
  with_items:  
    - { src: "{{ inventory_hostname }}/conf.d/", dest: . }    
  notify: restart nginx