- hosts: all
  roles:
    - common

- hosts: stg-web
  roles:
    - nginx
    - mysql
    - ruby
    - nodejs
    - live-study-stg
    - thefinn93.letsencrypt
  vars:
    letsencrypt_webroot_path: /var/www/Live-study
    letsencrypt_email: tatuya44511336@gmail.com # メールアドレス。通知がくることがある(?)
    letsencrypt_cert_domains: # 証明書を取得したいドメインのリスト
      - stg.live-study.work
    letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'